import { Component } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { Company } from 'src/app/classes/company/company';
import { CompanyService } from 'src/app/services/company/company.service';

//Spelling mistakes might be present, sorry :(
//delete if not using enum
enum Country {
  AFGHANISTAN = "Afghanistan",
  ALANDISLANDS = "Alandislands",
  ALBANIA = "Albania",
  ALGERIA = "Algeria",
  AMERICANSAMOA = "Americansamoa",
  ANDORRA = "Andorra",
  ANGOLA = "Angola",
  ANGUILLA = "Anguilla",
  ANTARCTICA = "Antarctica",
  ANTIGUAANDBARBUDA = "Antiguaandbarbuda",
  ARGENTINA = "Argentina",
  ARMENIA = "Armenia",
  ARUBA = "Aruba",
  AUSTRALIA = "Australia",
  AUSTRIA = "Austria",
  AZERBAIJAN = "Azerbaijan",
  BAHAMAS = "Bahamas",
  BAHRAIN = "Bahrain",
  BANGLADESH = "Bangladesh",
  BARBADOS = "Barbados",
  BELARUS = "Belarus",
  BELGIUM = "Belgium",
  BELIZE = "Belize",
  BENIN = "Benin",
  BERMUDA = "Bermuda",
  BHUTAN = "Bhutan",
  BOLIVIA = "Bolivia",
  BONAIRESINTEUSTATIUSSABA = "Bonaire, Sint Uestatius, Saba",
  BOSNIAANDHERZEGOVINA = "Bosnia and Herzegovina",
  BOTSWANA = "Botswana",
  BOUVETISLAND = "Bouvetisland",
  BRAZIL = "Brazil",
  BRITISHINDIANOCEANTERRITORY = "British Indian Ocean Territory",
  BRUNEIDARUSSALAM = "Brunei Darussalam",
  BULGARIA = "Bulgaria",
  BURKINAFASO = "Burkinafaso",
  BURUNDI = "Burundi",
  CAMBODIA = "Cambodia",
  CAMEROON = "Cameroon",
  CANADA = "Canada",
  CAPEVERDE = "Capeverde",
  CAYMANISLANDS = "Cayman Islands",
  CENTRALAFRICANREPUBLIC = "Central African Republic",
  CHAD = "Chad",
  CHILE = "Chile",
  CHINA = "China",
  CHRISTMASISLAND = "Christmas Island",
  COCOSKEELINGISLANDS = "Cocos Keeling Islands",
  COLOMBIA = "Colombia",
  COMOROS = "Comoros",
  CONGO = "Congo",
  CONGODEMOCRATICREPUBLIC = "Congo Democratic Repbulic",
  COOKISLANDS = "Cook Islands",
  COSTARICA = "Costa Rica",
  COTEDIVOIRE = "Côte d'Ivoire",
  CROATIA = "Croatia",
  CUBA = "Cuba",
  CURACAO = "Curacao",
  CYPRUS = "Cyprus",
  CZECHREPUBLIC = "Czech Republic",
  DENMARK = "Denmark",
  DJIBOUTI = "Djibouti",
  DOMINICA = "Dominica",
  DOMINICANREPUBLIC = "Dominican Republic",
  ECUADOR = "Ecuador",
  EGYPT = "Egypr",
  ELSALVADOR = "El Salvador",
  EQUATORIALGUINEA = "Equatorial Guinea",
  ERITREA = "Eritrea",
  ESTONIA = "Estonia",
  ETHIOPIA = "Ethiopia",
  FALKLANDISLANDS = "Falkland Islands",
  FAROEISLANDS = "Faroe Islands",
  FIJI = "Fiji",
  FINLAND = "Finland",
  FRANCE = "France",
  FRENCHGUIANA = "French Guiana",
  FRENCHPOLYNESIA = "French Polynesia",
  FRENCHSOUTHERNTERRITORIES = "French Southern Territories",
  GABON = "Gabon",
  GAMBIA = "Gambia",
  GEORGIA = "Georgia",
  GERMANY = "Germany",
  GHANA = "Ghana",
  GIBRALTAR = "Gibraltar",
  GREECE = "Greece",
  GREENLAND = "Greenland",
  GRENADA = "Grenada",
  GUADELOUPE = "Guadeloupe",
  GUAM = "Guam",
  GUATEMALA = "Guatemala",
  GUERNSEY = "Guernsey",
  GUINEA = "Guinea",
  GUINEABISSAU = "Guinea-Bissau",
  GUYANA = "Guyana",
  HAITI = "Haiti",
  HEARDISLANDMCDONALDISLANDS = "Heard Island and McDonald Islands",
  HOLYSEEVATICANCITYSTATE = "Holy See",
  HONDURAS = "Honduras",
  HONGKONG = "Hong Kong",
  HUNGARY = "Hungary",
  ICELAND = "Iceland",
  INDIA = "India",
  INDONESIA = "Indonesia",
  IRAN = "Iran",
  IRAQ = "Iraq",
  IRELAND = "Ireland",
  ISLEOFMAN = "Isle of Man",
  ISRAEL = "Israel",
  ITALY = "Italy",
  JAMAICA = "Jamaica",
  JAPAN = "Japan",
  JERSEY = "Jersey",
  JORDAN = "Jordan",
  KAZAKHSTAN = "Kazakhstan",
  KENYA = "Kenya",
  KIRIBATI = "Kiribati",
  KOREA = "South Korea",
  KOREADEMOCRATICPEOPLESREPUBLIC = "North Korea",
  KUWAIT = "Kuwait",
  KYRGYZSTAN = "Kyrgyzstan",
  LAOPEOPLESDEMOCRATICREPUBLIC = "Laos",
  LATVIA = "Latvia",
  LEBANON = "Lebanon",
  LESOTHO = "Lesotho",
  LIBERIA = "Liberia",
  LIBYANARABJAMAHIRIYA = "Libya",
  LIECHTENSTEIN = "Liechtenstein",
  LITHUANIA = "Lithuania",
  LUXEMBOURG = "Luxembourg",
  MACAO = "Macao",
  MACEDONIA = "Macedonia",
  MADAGASCAR = "Madagascar",
  MALAWI = "Malawi",
  MALAYSIA = "Malaysia",
  MALDIVES = "Maldives",
  MALI = "Mali",
  MALTA = "Malta",
  MARSHALLISLANDS = "Marshall Islands",
  MARTINIQUE = "Martinique",
  MAURITANIA = "Mauritania",
  MAURITIUS = "Mauritius",
  MAYOTTE = "Mayotte",
  MEXICO = "Mexico",
  MICRONESIA = "Micronesia",
  MOLDOVA = "Moldova",
  MONACO = "Monaco",
  MONGOLIA = "Mongolia",
  MONTENEGRO = "Montenegro",
  MONTSERRAT = "Montserrat",
  MOROCCO = "Morocco",
  MOZAMBIQUE = "Mozambique",
  MYANMAR = "Myanmar",
  NAMIBIA = "Namibia",
  NAURU = "Nauru",
  NEPAL = "Nepal",
  NETHERLANDS = "Netherlands",
  NEWCALEDONIA = "New Caledonia",
  NEWZEALAND = "New Zealand",
  NICARAGUA = "Nicaragua",
  NIGER = "Niger",
  NIGERIA = "Nigeria",
  NIUE = "Niue",
  NORFOLKISLAND = "Norfolk Island",
  NORTHERNMARIANAISLANDS = "Northern Mariana Islands",
  NORWAY = "Norway",
  OMAN = "Oman",
  PAKISTAN = "Pakistan",
  PALAU = "Palau",
  PALESTINIANTERRITORY = "Palestinian Territories",
  PANAMA = "Panama",
  PAPUANEWGUINEA = "Papua New Guinea",
  PARAGUAY = "Paraguay",
  PERU = "Peru",
  PHILIPPINES = "Philippines",
  PITCAIRN = "Pitcairn",
  POLAND = "Poland",
  PORTUGAL = "Portugal",
  PUERTORICO = "Puerto Rico",
  QATAR = "Qatar",
  REUNION = "Réunion",
  ROMANIA = "Romania",
  RUSSIANFEDERATION = "Russia",
  RWANDA = "Rwanda",
  SAINTBARTHELEMY = "Saint Barthélemy",
  SAINTHELENA = "Saint Helena",
  SAINTKITTSANDNEVIS = "Saint Kitts and Nevis",
  SAINTLUCIA = "Saint Lucia",
  SAINTMARTIN = "Saint Martin",
  SAINTPIERREANDMIQUELON = "Saint Pierre and Miquelon",
  SAINTVINCENTANDGRENADINES = "Saint Vincent and the Grenadines",
  SAMOA = "Samoa",
  SANMARINO = "San Marino",
  SAOTOMEANDPRINCIPE = "São Tomé and Principe",
  SAUDIARABIA = "Saudi Arabia",
  SENEGAL = "Senegal",
  SERBIA = "Serbia",
  SEYCHELLES = "Seychelles",
  SIERRALEONE = "Sierra Leone",
  SINGAPORE = "Singapore",
  SINTMAARTEN = "Sint Maarten",
  SLOVAKIA = "Slovakia",
  SLOVENIA = "Slovenia",
  SOLOMONISLANDS = "Solomon Islands",
  SOMALIA = "Somalia",
  SOUTHAFRICA = "South Africa",
  SOUTHGEORGIAANDSANDWICHISLANDS = "South Georgia and Sandwich Islands",
  SOUTHSUDAN = "South Sudan",
  SPAIN = "Spain",
  SRILANKA = "Sri Lanka",
  SUDAN = "Sudan",
  SURINAME = "Suriname",
  SVALBARDANDJANMAYEN = "Svalbard and Jan Mayen",
  SWAZILAND = "Eswatini",
  SWEDEN = "Sweden",
  SWITZERLAND = "Switzerland",
  SYRIANARABREPUBLIC = "Syria",
  TAIWAN = "Taiwan",
  TAJIKISTAN = "Tajikistan",
  TANZANIA = "Tanzania",
  THAILAND = "Thailand",
  TIMORLESTE = "Timor-Leste",
  TOGO = "Togo",
  TOKELAU = "Tokelau",
  TONGA = "Tonga",
  TRINIDADANDTOBAGO = "Trinidad and Tobago",
  TUNISIA = "Tunisia",
  TURKEY = "Turkey",
  TURKMENISTAN = "Turkmenistan",
  TURKSANDCAICOSISLANDS = "Turks and Caicos Islands",
  TUVALU = "Tuvalu",
  UGANDA = "Uganda",
  UKRAINE = "Ukraine",
  UNITEDARABEMIRATES = "United Arab Emirates",
  UNITEDKINGDOM = "United Kingdom",
  UNITEDSTATES = "United States",
  UNITEDSTATESOUTLYINGISLANDS = "United States Outlying Islands",
  URUGUAY = "Uruguay",
  UZBEKISTAN = "Uzbekistan",
  VANUATU = "Vanuatu",
  VENEZUELA = "Venezuela",
  VIETNAM = "Vietnam",
  VIRGINISLANDSBRITISH = "Britsh Virgin Islands",
  VIRGINISLANDSUS = "U.S. Virgin Islands",
  WALLISANDFUTUNA = "Wallis and Futuna",
  WESTERNSAHARA = "Western Sahara",
  YEMEN = "Yemen",
  ZAMBIA = "Zambia",
  ZIMBABWE = "Zimbabwe"
}

@Component({
  selector: 'app-register-form',
  templateUrl: './register-form.component.html',
  styleUrls: ['./register-form.component.css']
})
export class RegisterFormComponent{

  //delete if not using enum
  eCountry = Country;

  company = this.fb.group({
    vatNumber: ['', [Validators.required, Validators.pattern('^[A-Za-z0-9 ]+$')]],
    companyName: ['', [Validators.required, Validators.pattern('[a-zA-Z ]+')]],
    email: ['', [Validators.required, Validators.pattern("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}$")]],
    streetName: ['', [Validators.required, Validators.pattern('[a-zA-Z ]+')]],
    houseNumber: ['', [Validators.required, Validators.pattern("^[0-9]*$")]],
    postcode: ['', [Validators.required, Validators.pattern("^[0-9]*$")]],
    city: ['', [Validators.required, Validators.pattern('[a-zA-Z ]+')]],
    country: ['', [Validators.required, Validators.pattern('[a-zA-Z ]+')]],
    businessActivity: ['', [Validators.nullValidator, Validators.pattern('[a-zA-Z ]+')]],
    taxOffice: ['', [Validators.nullValidator, Validators.pattern('[a-zA-Z ]+')]]
  })

  constructor(private fb: FormBuilder,
    private cs: CompanyService) { }

  onSubmit() {
    this.cs.register(new Company(
      this.company.value.vatNumber,
      this.company.value.companyName,
      this.company.value.email,
      this.company.value.streetName,
      this.company.value.houseNumber,
      this.company.value.postcode,
      this.company.value.city,
      this.company.value.country,
      this.company.value.businessActivity,
      this.company.value.taxOffice))
  }
}
